Run method
zuevmaxim/kotlin-fuzzer pull request #1
Opened 2020-03-06 11:38 UTC by zuevmaxim

2020-03-11 15:14 UTC, qwwdfsad requested changes

2020-03-11 15:14 UTC, qwwdfsad commented on build.gradle
> +    compile "org.jetbrains.kotlin:kotlin-reflect:1.3.50"
Чтобы везде не дублировать константы с версиями, особенно когда есть несколько артефактов одной версии, удобно вынести её в gradle.properties:
```
// gradle.properties
kotlin_version=1.3.50

// build.gradle
compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
```

2020-03-11 15:14 UTC, qwwdfsad commented on build.gradle
> +plugins {
Я бы рекомендовал пользоваться сразу `build.gradle.kts`: сильно понятнее и все рефакторинги + code completion нормально работают из IDE.
Не настаиваю, на твое усмотрение, можно отдельным PR

2020-03-11 15:14 UTC, qwwdfsad commented on src/test/kotlin/ru/example/kotlinfuzzer/MethodRunnerTest.kt
> +    fun test() {
лучше давать тестам осмысленные имена

2020-03-11 15:14 UTC, qwwdfsad commented on build.gradle
> +    compile "org.jetbrains.kotlin:kotlin-reflect:1.3.50"
И лучше пользоваться последней версией Котлина, 1.3.70

2020-03-11 15:14 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/BytesClassLoader.kt
> +            it!!.readAllBytes()
Этот метод есть начиная с 9-ой Java, а в гредле прописан `jvmTarget = 1.8`. По этой же причине `./gradlew build` падает.

Лучше всего пользоваться последней стабильной версией -- 11-ой

2020-03-11 15:14 UTC, qwwdfsad commented on src/test/kotlin/ru/example/kotlinfuzzer/MethodRunnerTest.kt
> +            assertTrue(doneMethods.contains(it))
выглядит как кандидат на parameterized test

2020-03-11 15:14 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/main.kt
> +            |3. method to execute name
method to execute name -> method name to execute

2020-03-11 15:14 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/MemoryClassLoader.kt
> +    @Throws(ClassNotFoundException::class)
Если не планируешь вызывать этот код из джавы, то `@Throws` можно не навешивать

2020-03-11 15:14 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/MemoryClassLoader.kt
> +        } else super.loadClass(name, resolve)
Лучше придерживаться консистентного стиля: либо в обоих ветках использовать фигурные скобки, либо в обоих не использовать

2020-03-12 22:29 UTC, zuevmaxim commented on build.gradle
> +    compile "org.jetbrains.kotlin:kotlin-reflect:1.3.50"
После перехода на build.gradle.kts нет повторений версии

2020-03-13 07:00 UTC, qwwdfsad approved these changes

2020-03-20 14:58 UTC, merged