Parallel corpus minimization
zuevmaxim/kotlin-fuzzer pull request #24
Opened 2020-07-17 12:47 UTC by zuevmaxim

#18 #22

2020-08-27 16:28 UTC, qwwdfsad approved these changes

2020-08-27 16:28 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/CorpusMinimizer.kt
> +        check(executionResult is ExecutedInput) { "Only success inputs expected." }
Очень полезный навык при написании любого кода: при проверке любого условия добавлять в текст ошибки контекст. В данном случае это FailedInput

2020-08-27 16:28 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/CorpusMinimizer.kt
> +            .also { runAllInputs(it) }
Code style: более идиоматично было бы написать `List<Input>.runAll()`

2020-08-27 16:31 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/CorpusMinimizer.kt
> +        check(executionResult is ExecutedInput) { "Only success inputs expected." }
Добавить "but got FailInput"?

2020-08-27 17:43 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/CorpusMinimizer.kt
> +        check(executionResult is ExecutedInput) { "Only success inputs expected." }
В итоге "Execution failed with an exception but only success inputs expected."

2020-08-27 22:05 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/CorpusMinimizer.kt
> +        check(executionResult is ExecutedInput) { "Only success inputs expected." }
Добавить саму проблему в сообщение. По константой строке довольно тяжело понять, что пошло не так.
Как вариант: `"Successful input was expected, but got: $executionResult"`

2020-08-27 22:06 UTC, qwwdfsad requested changes
.

2020-08-28 14:15 UTC, qwwdfsad approved these changes

2020-08-28 15:31 UTC, merged