Add fuzzer
zuevmaxim/kotlin-fuzzer pull request #3
Opened 2020-04-06 23:13 UTC by zuevmaxim

2020-05-15 12:49 UTC, qwwdfsad requested changes

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/cli/CommandLineArgs.kt
>      val className by parser.option(ArgType.String, description = "Target class name").required()
[nit] между приватными и публичными декларациями удобно ставить отступ, чтобы публичный API был логически выделен

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/cli/main.kt
> +        println(e.message)
e.printstacktrace обычно информативнее

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/cli/CommandLineArgs.kt
> +    fun threadsNumber() = threadsNumber.also {
Лучше такие вещи делать тоже `val`, но с нетривиальным getter'ом.

Но в твоем случае проще всего валидировать значения в конструкторе:
```
val threadsNumber by parser.option(ArgType.Int, description = "Number of threads for workers.")
init {
        require(threadsNumber > 0, "...")
 }
```

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/coverage/CoverageResult.kt
> +    fun ratio(other: CoverageResult) = listOf(
без перевода строки читается как один метод

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/coverage/CoverageResult.kt
> +    fun ratio(other: CoverageResult) = listOf(
И про naming: `ratio` чего? :)

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/coverage/MethodRunner.kt
> +    /** Run specified function with coverage. */
Метод делает не то, что написано в документации.
Он исполняет *произвольную* функцию, а coverage считает по predefined пакетам/классам

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/exceptions/ExceptionHandlingThreadFactory.kt
> +class ExceptionHandlingThreadFactory(fuzzer: Fuzzer) : ThreadFactory {
Весь этот класс можно заменить одной лямбдой:

```
 private val threadPool = Executors.newFixedThreadPool(arguments.threadsNumber()) { r ->
        Thread(r).apply { setUncaughtExceptionHandler { t, e -> stop(e) } }
    }
```

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/Logger.kt
> +    companion object {
потерян private

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/PriorityThreadPool.kt
> +class PriorityThreadPool(nThreads: Int) {
Unused код

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/TargetMethod.kt
> +    private val method: Method
Более понятно будет записать так, без init блока
```
  private val method: Method = targetClass.declaredMethods
        .filter { it.name == methodName }
        .filter { checkMethodSignature(it) }
        .single()
```

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/TargetMethod.kt
> +        val result: Result<Int> = try {
можно воспользоваться функцией `runCatching`, которая именно это и делает

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/input/ByteArrayHash.kt
> +    val hash = Hash(bytes)
получается, что в момент перехода Input -> ExecutedInput, хэш пересчитывается лишний раз, хотя этого можно не делать

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/input/ExecutedInput.kt
> +    override fun mutate(mutator: InputMutator) = this.also {
а может тогда mutator.mutate должен возвращать свой аргумент?

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/inputhandlers/InputMinimizer.kt
> +class InputMinimizer<T : Input>(private val methodRunner: MethodRunner, private val targetMethod: TargetMethod) {
Масло масляное получается.
Было бы неплохо иметь короткое описание того, как именно вход минимизируется

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/inputhandlers/InputMutator.kt
> +/** Mutates input and submits new tasks. */
Аналогично здесь

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/TargetMethod.kt
> +    private fun checkMethodSignature(method: Method): Boolean {
codestyle: название check в Котлине подразумевает, что функция ничего не возвращает, но может кинуть исключение.
У тебя скорее `isApplicableMethodSignature`

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/inputhandlers/InputRunner.kt
> +                targetMethod.execute(input) { result = it }
функция ведь абсолютно синхронна, почему она вызывает callback вместо возвращения значения?

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/inputhandlers/InputRunner.kt
> +        if (result.isFailure) {
со связкой result.onFailure и result.onSuccess не понадобятся ни `!!`, ни `return`

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/inputhandlers/InputTask.kt
> +    protected open val forceSave = false
всё состояние должно идти перед функциями. И в этом месте не помешала бы документация

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/inputhandlers/MutationTask.kt
> +        lock.lock()
Такое использование очень error-prone, unlock нужно всегда вызывать в finally-блоке.
В Котлине для этого есть конструкция `lock.withLock {}`

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/inputhandlers/MutationTask.kt
> +            condition.await(MAX_SLEEP_TIME_S, TimeUnit.SECONDS)
А зачем после каждой мутации ждать condition'а, ты таким способ неявно формируешь очередь исполнения?

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/mutation/AddSubtractMutations.kt
> +private fun numberMutation(): Int {
к этому методу тоже нужна документация, неочевидно, что он делает

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/mutation/MutationFactory.kt
> +        InsertBytesMutation()
Code style, запятые обычно идут в конце. Тут поможет идеевский автоформат (ctrl/cmd + alt + L)

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/mutation/ReplaceInterestingValueMutations.kt
> +        val interestingValues = listOf<Byte>(0, 1, -1, 2, -2, 127, -128, 64, -64, 100, -100)
тут тоже нужен комментарий

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/mutation/ReplaceNumberMutation.kt
> +        val buffer = ByteBuffer.allocate(numberSize).put(bytes, index, numberSize).flip()
[optional] каждый раз аллоцировать буффер все таки дороговато. Возможно проще в `mutateNumber` принимать `long` (как самый широкий тип) и `sizeInBytes` и оперировать с ними

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/mutation/ReplaceTextNumberMutation.kt
> +        internal const val MAX_REPLACE_VALUE = 1000
такие константы можно сразу на top-level в файле выносить. И лучше бы названия константы было сразу понятно, что именно она контролирует.

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/mutation/ReplaceTextNumberMutation.kt
> +    private fun randomNumber() = Random.nextInt(2 * MAX_REPLACE_VALUE + 1) - MAX_REPLACE_VALUE
это случайно не то же самое, что `Random.nextInt(-const, const + 1)`?

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/mutation/SpliceAnotherInputMutation.kt
> +class SpliceAnotherInputMutation(private val storage: Storage) : Mutation {
нужна документация

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/storage/ContextFactory.kt
> +    fun acquire(): Context = localContext.get()
этот метод не берет ничего во владение, просто достает текущий контекст.
Кажется, от этого класса можно совсем избавиться и положить `val localContext` куда-нибудь в fuzzer

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/storage/FileStorage.kt
> +class FileStorage(workingDirectory: File, name: String) {
кажется, эта логика может быть помещена в класс `Storage`, чтобы избавиться от лишних абстракций

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/storage/Storage.kt
> +    fun isBestInput(input: ExecutedInput) = isBestInput(input, bestCoverage.get())
нужен отступ

2020-05-15 12:49 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/storage/Storage.kt
> +    fun save(input: ExecutedInput, force: Boolean = false) {
нужна документация, что такое "maximum score input"

2020-05-16 09:03 UTC, zuevmaxim commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/storage/ContextFactory.kt
> +    fun acquire(): Context = localContext.get()
Я только переименую. Я не хочу передавать в InputTask fuzzer, ведь достаточно только contexFactory, которая выполняет конкретную полезную задачу

2020-05-16 09:05 UTC, zuevmaxim commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/storage/FileStorage.kt
> +class FileStorage(workingDirectory: File, name: String) {
Так FileStorage нужен несколько раз: crashes, corpus, executed

2020-05-16 09:37 UTC, zuevmaxim commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/mutation/ReplaceInterestingValueMutations.kt
> +        val interestingValues = listOf<Byte>(0, 1, -1, 2, -2, 127, -128, 64, -64, 100, -100)
Хм, не знаю, как нормально прокомментировать(мне казалось, что все понятно). Получилось "Boundary Byte values"

2020-05-16 09:45 UTC, zuevmaxim commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/mutation/MutationFactory.kt
> +        InsertBytesMutation()
Так просто было удобно отключать мутации комментированием, уже не актуально, наверное.

2020-05-16 09:46 UTC, zuevmaxim commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/mutation/AddSubtractMutations.kt
> +private fun numberMutation(): Int {
Поменял название

2020-05-16 09:53 UTC, zuevmaxim commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/inputhandlers/MutationTask.kt
> +            condition.await(MAX_SLEEP_TIME_S, TimeUnit.SECONDS)
MutationTask мутирует входы из корпуса, когда очередь пустеет. Тут была проблема. Неразумно сильно наполнять очередь: во-первых, много памяти тратится, а, во-вторых, лучше мутировать входы с хорошим score => если один раз много намутировать не слишком хороший вход, то результат будет таким же не слишком хорошим, а очередь придется долго разгребать, хотя мы могли уже найти хороший вход, который хочется мутировать. Хотелось сделать так, чтобы очередь наполнялась небольшими порциями и только когда нужно.

2020-05-16 10:08 UTC, zuevmaxim commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/input/ByteArrayHash.kt
> +    val hash = Hash(bytes)
С lazy будет нормально?

2020-05-16 11:08 UTC, zuevmaxim commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/inputhandlers/InputRunner.kt
> +                targetMethod.execute(input) { result = it }
Сделано так, потому что Result нельзя возвращать. Или использовать -Xallow-result-return-type?

2020-05-16 12:10 UTC, zuevmaxim commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/mutation/ReplaceNumberMutation.kt
> +        val buffer = ByteBuffer.allocate(numberSize).put(bytes, index, numberSize).flip()
Теперь аллоцирую один буффер размера 4 => всего 4 буффера

2020-05-16 14:12 UTC, zuevmaxim commented on src/main/kotlin/ru/example/kotlinfuzzer/cli/CommandLineArgs.kt
> +    fun threadsNumber() = threadsNumber.also {
Getter не разрешен, когда by, а конструктор тоже не подходит, так как threadsNumber еще не инициализировано

2020-06-20 13:26 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/input/ByteArrayHash.kt
> +    val hash = Hash(bytes)
так а почему просто в конструкторе его не передавать?

2020-06-20 13:26 UTC, qwwdfsad commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/inputhandlers/InputRunner.kt
> +                targetMethod.execute(input) { result = it }
Можно обновиться до 1.4-M2, там уже можно

2020-06-20 14:13 UTC, qwwdfsad requested changes

2020-06-20 14:13 UTC, qwwdfsad commented on build.gradle.kts
> +    // time format
кстати его же можно пофаззить :)

2020-06-20 14:13 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/classload/CodeCoverageClassTransformer.kt
>  object CodeCoverageClassTransformer {
Кажется, гораздо понятнее будет, если удалить этот объект и заменить его приватной функцией в Loader'е

2020-06-20 14:13 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/classload/Loader.kt
> +        private fun pathsToUrls(paths: List<String>) = paths.map { File(it).toURI().toURL() }
Можно не думать в терминах "этот метод должен быть статичным" и объявлять его сразу членом класса.
Если очень хочется сделать метод статичным (например, чтобы случайно не захватить в scope this), лучше делать его приватным в том же файле (вне класса)

2020-06-20 14:13 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/classload/Loader.kt
> +    fun classLoader(): ClassLoader = memoryClassLoader
fun -> val

2020-06-20 14:13 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/coverage/MethodRunner.kt
> +    getClasses: (LoggerRuntime) -> Collection<ByteArray>
Все использования конструктора выглядят как `MethodRunner { loader.load(it) }`, наверное это в таком случае должен делать конструктор

2020-06-20 14:13 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/inputhandlers/Context.kt
> +class Context(
Наверное, `FuzzerContext`? Небольшая документация тоже не повредит

2020-06-20 14:13 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/inputhandlers/InputMinimizer.kt
> + * A minimization is possible if minimized input has the same properties as the original.
`has the same properties` -> has the same coverage или produces the same result?

2020-06-20 14:13 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/input/Input.kt
> +open class Input(val data: ByteArray) : ByteArrayHash(data) {
документация не повредит

2020-06-20 14:13 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/cli/main.kt
> +        e.printStackTrace()
можно убрать try/catch вообще, JVM и так напечатает исключение и exit code будет не 0, что правильнее

2020-06-20 14:13 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/coverage/InstanceCreator.kt
> +private const val MAX_ARRAY_SIZE = 1000
Стоит сделать этот параметр конфигурируемым

2020-06-20 14:13 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/FuzzerArgs.kt
> +        require(threadsNumber >= 1) { "Number of threads should be at least one." }
maxTaskQueueSize тоже нужно валидировать

2020-06-20 14:13 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/Logger.kt
> +    fun log(message: String) = FileWriter(logFile, true).use { out ->
Открывать-закрывать файл на каждую запись в лог не очень эффективно.
Лучше держать открытым файл весь процесс фаззинга, и иногда флашить

2020-06-20 14:13 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/Logger.kt
> +            print("\u001b[1A\u001b[2K")
странный print

2020-06-20 14:13 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/input/ExecutedInput.kt
> +    else InputMinimizer<ExecutedInput>(methodRunner, targetMethod).minimize(this) { newInput ->
такие отступы очень плохо читаются, пользуйся пожалуйста в таких случаях block body (`{ ... }`)

2020-06-20 20:01 UTC, zuevmaxim commented on src/main/kotlin/ru/example/kotlinfuzzer/fuzzing/input/ByteArrayHash.kt
> +    val hash = Hash(bytes)
Hash на самом деле используется только при сохранении, проще будет там его и посчитать, а ByteArrayHash вообще не нужен

2020-06-20 20:59 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/Logger.kt
> +            print("\u001b[1A\u001b[2K")
Это очистка строчки, чтобы сообщение fuzzer-а стояли на месте, а не сыпались бесконечно. Правда, это не работает не в терминале.

2020-06-20 21:05 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/classload/CodeCoverageClassTransformer.kt
>  object CodeCoverageClassTransformer {
Да. Это была попытка изолировать специфичную для jacoco логику, но потом она расползлась.

2020-06-20 21:14 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/coverage/MethodRunner.kt
> +    getClasses: (LoggerRuntime) -> Collection<ByteArray>
Конструктор вызывается всего в одном месте(ну без тестов), зато MethodRunner не знает, откуда берется этот набор классов(так себе достижение, конечно, с учетом остальных зависимоетей), я считаю что так более правильно, а использование сильно не страдает.
Хотя и MethodRunner, и Loader подвергнутся изменениям при переходе с jacoco...

2020-06-20 21:23 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/inputhandlers/InputMinimizer.kt
> + * A minimization is possible if minimized input has the same properties as the original.
Комментарий размазан между InputMinimizer, FailInput, ExecutedInput.

2020-06-20 21:41 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/Logger.kt
> +    fun log(message: String) = FileWriter(logFile, true).use { out ->
Сейчас логгируется только fail => это достаточно редко если unique exceptions. Потом становится больше логов, так что я сделал.

2020-06-20 21:46 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/coverage/InstanceCreator.kt
> +private const val MAX_ARRAY_SIZE = 1000
Этот класс вообще не очень нужен(ну нужен только метод constructDefault(clazz: Class<*>?): Any?). Проще прописать, что требуется класс с конструктором без параметров. Кажется, это самый частый и самый логичный случай.

2020-06-22 12:56 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/coverage/MethodRunner.kt
> +    getClasses: (LoggerRuntime) -> Collection<ByteArray>
Да,  теперь я понял, что MethodRunner и Loader неразделимы, так как их поведение вызвано спецификой использования jacoco. Теперь Loader спрятан.

2020-06-22 13:02 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/coverage/InstanceCreator.kt
> +private const val MAX_ARRAY_SIZE = 1000
Сделать так?

2020-06-26 07:37 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/coverage/InstanceCreator.kt
> +private const val MAX_ARRAY_SIZE = 1000
Да, давай

2020-06-26 07:38 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/Logger.kt
> +            print("\u001b[1A\u001b[2K")
Тогда наверное можно проверять, что System.console != null

2020-06-26 07:48 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/coverage/CoverageRunnerFactory.kt
> +object CoverageRunnerFactory {
Фабрики-компаньоны это Spring way для Java :)

Одной top-level функции `createCoverageRunner` в файле `CoverageRunner` было бы достаточно

2020-07-02 20:46 UTC, zuevmaxim commented on build.gradle.kts
> +    // time format
Он исключений не бросает(

2024-04-09 09:26 UTC, merged