Cover java
zuevmaxim/kotlin-fuzzer pull request #36
Opened 2020-08-26 11:13 UTC by zuevmaxim

2020-08-27 16:21 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/coverage/jwp/instrumenting.kt
> +    if (classesToRetransform.isNotEmpty()) {
Без этого if что-то ломается?

2020-08-27 16:21 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/mutation/AddSubtractMutations.kt
> +        return buffer.apply {
предыдущий код был понятнее

2020-08-27 16:23 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/coverage/jwp/instrumenting.kt
> +    if (classesToRetransform.isNotEmpty()) {
Да, там 
* java.lang.instrument ASSERTION FAILED *: “numClasses != 0” at JPLISAgent.c line: 1102
Exception in thread “main” java.lang.NullPointerException
 at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
 at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
 at kotlinx.fuzzer.instrumenting.InstrumentingKt.retransformLoadedClasses(instrumenting.kt:25)
 at kotlinx.fuzzer.instrumenting.InstrumentingKt.transform(instrumenting.kt:13)
 at kotlinx.fuzzer.instrumenting.JwpCoverageRunner.<init>(JwpCoverageRunner.kt:15)
 at kotlinx.fuzzer.coverage.CoverageRunnerKt.createCoverageRunner(CoverageRunner.kt:14)
 at kotlinx.fuzzer.fuzzing.inputhandlers.FuzzerContext.<init>(FuzzerContext.kt:15)
 at kotlinx.fuzzer.Fuzzer.<init>(Fuzzer.kt:32)
 at kotlinx.fuzzer.cli.MainKt.main(main.kt:19)

2020-08-27 16:23 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/mutation/AddSubtractMutations.kt
> +        return buffer.apply {
А на java8 так нельзя

2020-08-27 22:07 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/coverage/jwp/instrumenting.kt
> +    if (classesToRetransform.isNotEmpty()) {
Тогда стоит об этом написать комментарий.
Любое неочевидное место -- комментарий, зачем оно в коде. Через три месяца никто не вспомнит, почему было принято то или иное решение, поэтому важно отражать это в комментариях

2020-08-27 22:07 UTC, qwwdfsad requested changes
"You need to leave a comment indicating the requested changes."

2020-08-28 13:53 UTC, qwwdfsad approved these changes

2020-08-28 14:23 UTC, merged