Update README
zuevmaxim/kotlin-fuzzer pull request #4
Opened 2020-05-19 12:24 UTC by zuevmaxim

2020-05-19 13:03 UTC, qwwdfsad requested changes

2020-05-19 13:03 UTC, qwwdfsad commented on README.md
> +## Before fuzzering
```suggestion
## Before fuzzing
```

2020-05-19 13:03 UTC, qwwdfsad commented on README.md
> +    * *bytes* is an input(from corpus or generated one)
```suggestion
    * *bytes* is an input for your algorithm (either from the predefined corpus or generated one)
```

2020-05-19 13:03 UTC, qwwdfsad commented on README.md
> +    * Return value represents status of input:
По документации не очень понятно, откуда этот статус взять.
Можно написать маленький семпл кода

2020-05-19 13:03 UTC, qwwdfsad commented on README.md
> +2. Create "init" directory and add initial corpus into it
Выше нигде не написано, что такое корпус.

Неплохо дать чуть более подробное описание в первом параграфе

2020-06-20 13:19 UTC, qwwdfsad approved these changes

2020-08-28 14:17 UTC, qwwdfsad approved these changes

2020-08-28 14:17 UTC, qwwdfsad commented on README.md
> +* [apache/commons-compress: Decompression fails with ArrayIndexOutOfBoundsException(1)](https://issues.apache.org/jira/browse/COMPRESS-516) **fixed**
Не забудь про Ktor :)

2020-08-28 14:21 UTC, zuevmaxim commented on README.md
> +* [apache/commons-compress: Decompression fails with ArrayIndexOutOfBoundsException(1)](https://issues.apache.org/jira/browse/COMPRESS-516) **fixed**
Да, потом добавлю

2020-08-28 14:22 UTC, merged