Add corpus minimization
zuevmaxim/kotlin-fuzzer pull request #7
Opened 2020-05-22 10:46 UTC by zuevmaxim

2020-06-20 13:18 UTC, qwwdfsad requested changes

2020-06-20 13:18 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/cli/CommandLineArgs.kt
> +    val minimize by parser.option(ArgType.Boolean, description = "Corpus minimization").default(false)
лучше дать небольшое пояснение, что именно включает в себя минимизация

2020-06-20 13:18 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/CorpusMinimizer.kt
> + * Implements greedy solution of coverage problem.
<зануда>maximum coverage problem</зануда>

2020-06-20 13:18 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/CorpusMinimizer.kt
> +                print("\u001b[1A\u001b[2K")
а что это за `print`?

2020-06-20 13:18 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/CorpusMinimizer.kt
> +                println("total coverage is $total\n")
Если это для локальной отладки, то лучше удалить.
Если для пользовательской, то лучше делегировать в какой-нибудь логгер, который можно глобально конфигурировать per-fuzzing

2020-06-20 13:18 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/cli/main.kt
> +            corpusMinimizer.minimize(File(fuzzArgs.workingDirectory))
Наверное те, кто минимизируют корпус, хотят сразу же поверх него запустить fuzzing?

2020-06-24 09:23 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/cli/main.kt
> +            corpusMinimizer.minimize(File(fuzzArgs.workingDirectory))
Нет, мне кажется, что это разные задачи. Минимизация корпуса в моем представлении нужна после запуска фаззера, чтобы потом взять этот набор в качесте корректных тестов. До запуска фаззера, конечно, можно запустить, но если мы решим, что forceSave корпусных входов не нужен, это само произойдет.

2020-06-26 07:36 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/cli/main.kt
> +            corpusMinimizer.minimize(File(fuzzArgs.workingDirectory))
Тогда в описание этой опции нужно четко прописать её назначение, сйчас это вообще неочевидно

2020-06-26 07:36 UTC, qwwdfsad approved these changes
Отлично, можно мерджить по модулю последнего комментария

2020-08-28 14:06 UTC, merged