Ignore equal exceptions
zuevmaxim/kotlin-fuzzer pull request #9
Opened 2020-05-29 12:07 UTC by zuevmaxim

2020-06-20 13:02 UTC, qwwdfsad requested changes

2020-06-20 13:02 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/cli/CommandLineArgs.kt
> +        .default(false)
А почему `false` по умолчанию?

2020-06-20 13:02 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/input/ExceptionWrapper.kt
> +        private fun cutReflection(trace: Array<StackTraceElement?>) = trace
обычно это `remove` или `trim`

2020-06-20 13:02 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/input/ExceptionWrapper.kt
> +class ExceptionWrapper(internal val e: Throwable) {
а почему не `private`?

2020-06-20 13:02 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/input/ExceptionWrapper.kt
> +    private fun equalStackTrace(trace1: Array<StackTraceElement?>?, trace2: Array<StackTraceElement?>?): Boolean {
Сейчас непонятно, насколько действенен такой способ.

Более натуральным может быть такой способ (который сразу же и решает проблема "непонятного" `ExceptionWrapper`):

1) Завести класс под условным названием `ExceptionsStaorage`/`FailureStorage`/`ExceptionDeduplicator`
2) Инкапсулировать логику дедупликации в нём
3) В нём же следить за статистикой (сколько эксепшном задедуплицировалось, каких)
4) Под специальным флагом (или в конце запуска) эту статистику выводить на консоль

2020-06-20 13:02 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/input/ExceptionWrapper.kt
> +    constructor(element: StackTraceElement) : this(element.fileName, element.lineNumber)
а почему сравниваются только номера строк и названия файлов, но не классов/методов?

2020-06-24 09:37 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/cli/CommandLineArgs.kt
> +        .default(false)
Не знаю:) Опасное изменение логики отчтета об ошибках
Но это очень удобно, так что включу по умолчанию
Сейчас только есть проблема, что если пользовательский код использует reflection, то все обрежется до его использования.

2020-06-24 09:39 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/input/ExceptionWrapper.kt
> +class ExceptionWrapper(internal val e: Throwable) {
Я думал, что для тестов потребуется, а потом забыл

2020-06-24 11:05 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/input/ExceptionWrapper.kt
> +    constructor(element: StackTraceElement) : this(element.fileName, element.lineNumber)
На то была какая-то причина, но я ее забыл. Кажется, я таким образом пытался обойти reflection, который меняет названия классов и методов от запуска к запуску. Сейчас уже неактуально.

2020-06-24 11:07 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/input/ExceptionWrapper.kt
> +    private fun equalStackTrace(trace1: Array<StackTraceElement?>?, trace2: Array<StackTraceElement?>?): Boolean {
Да, так и планировалось изначально, а в процессе реализации так-то модифицировалось. Я пока сделал только 1 и 2, а 3 и 4 я пока не очень понял зачем такая функциональность нужна, предлагаю отложить на потом

2020-06-24 11:21 UTC, zuevmaxim commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/input/ExceptionWrapper.kt
> +    private fun equalStackTrace(trace1: Array<StackTraceElement?>?, trace2: Array<StackTraceElement?>?): Boolean {
2 все еще делается с помощью ExceptionWrapper. Я переименовал в StacktraceEqualException.

2020-06-26 07:40 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/cli/CommandLineArgs.kt
> +        .default(false)
На такие вещи стоит заводить issue в гитхаб репозитории, чтобы не забыть их в будущем

2020-06-26 07:45 UTC, qwwdfsad requested changes

2020-06-26 07:45 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/storage/exceptions/StacktraceEqualException.kt
> +    val fileName: String?, val lineNumber: Int, val className: String, val methodName: String
А чем это теперь отличается от стандартного `StackTraceElement`? Всякие declared class и module name у них все равно одинаковые будут, зачем тогда отдельный класс?

Если он вдруг зачем-то нужен, он все равно должен быть приватным и вложенным в `StacktraceEqualException`, в тестах лучше настолько в детали реализации не зарываться

2020-06-26 07:45 UTC, qwwdfsad commented on src/main/kotlin/kotlinx/fuzzer/fuzzing/storage/Storage.kt
> +class Storage(workingDirectory: File, private val ignoreEqualExceptions: Boolean, getLogger: () -> Logger) {
а может это поведение сделать безусловным, раз оно все равно крайне полезно?

2020-07-02 16:34 UTC, qwwdfsad approved these changes

2020-07-02 16:47 UTC, merged